// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: access.sql

package dbgen

import (
	"context"
)

const addAccess = `-- name: AddAccess :one
INSERT INTO accesses (api_key, refresh_token, role)
VALUES ($1, $2, $3)
RETURNING id, api_key, refresh_token, role, created_at, updated_at
`

type AddAccessParams struct {
	ApiKey       string `json:"api_key"`
	RefreshToken string `json:"refresh_token"`
	Role         string `json:"role"`
}

func (q *Queries) AddAccess(ctx context.Context, arg *AddAccessParams) (*Access, error) {
	row := q.db.QueryRow(ctx, addAccess, arg.ApiKey, arg.RefreshToken, arg.Role)
	var i Access
	err := row.Scan(
		&i.ID,
		&i.ApiKey,
		&i.RefreshToken,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const editAccess = `-- name: EditAccess :one
UPDATE accesses
SET refresh_token = $2,
  updated_at = now()
WHERE id = $1
RETURNING id, api_key, refresh_token, role, created_at, updated_at
`

type EditAccessParams struct {
	ID           int64  `json:"id"`
	RefreshToken string `json:"refresh_token"`
}

func (q *Queries) EditAccess(ctx context.Context, arg *EditAccessParams) (*Access, error) {
	row := q.db.QueryRow(ctx, editAccess, arg.ID, arg.RefreshToken)
	var i Access
	err := row.Scan(
		&i.ID,
		&i.ApiKey,
		&i.RefreshToken,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAccess = `-- name: GetAccess :one
SELECT id, api_key, refresh_token, role, created_at, updated_at FROM accesses
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccess(ctx context.Context, id int64) (*Access, error) {
	row := q.db.QueryRow(ctx, getAccess, id)
	var i Access
	err := row.Scan(
		&i.ID,
		&i.ApiKey,
		&i.RefreshToken,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAccesses = `-- name: ListAccesses :many
SELECT id, api_key, refresh_token, role, created_at, updated_at
FROM accesses
ORDER BY created_at DESC
`

func (q *Queries) ListAccesses(ctx context.Context) ([]*Access, error) {
	rows, err := q.db.Query(ctx, listAccesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Access{}
	for rows.Next() {
		var i Access
		if err := rows.Scan(
			&i.ID,
			&i.ApiKey,
			&i.RefreshToken,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAccess = `-- name: RemoveAccess :exec
DELETE FROM accesses
WHERE id = $1
`

func (q *Queries) RemoveAccess(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, removeAccess, id)
	return err
}
