// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cart.sql

package dbgen

import (
	"context"
)

const addCart = `-- name: AddCart :one
INSERT INTO carts (product_name, qty, buyer, price, order_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_name, qty, buyer, price, order_id, created_at, updated_at
`

type AddCartParams struct {
	ProductName string  `json:"product_name"`
	Qty         int32   `json:"qty"`
	Buyer       string  `json:"buyer"`
	Price       float64 `json:"price"`
	OrderID     int64   `json:"order_id"`
}

func (q *Queries) AddCart(ctx context.Context, arg *AddCartParams) (*Cart, error) {
	row := q.db.QueryRow(ctx, addCart,
		arg.ProductName,
		arg.Qty,
		arg.Buyer,
		arg.Price,
		arg.OrderID,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.ProductName,
		&i.Qty,
		&i.Buyer,
		&i.Price,
		&i.OrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const editCart = `-- name: EditCart :one
UPDATE carts
SET qty = $2,
  price = $3,
  updated_at = now()
WHERE id = $1
RETURNING id, product_name, qty, buyer, price, order_id, created_at, updated_at
`

type EditCartParams struct {
	ID    int64   `json:"id"`
	Qty   int32   `json:"qty"`
	Price float64 `json:"price"`
}

func (q *Queries) EditCart(ctx context.Context, arg *EditCartParams) (*Cart, error) {
	row := q.db.QueryRow(ctx, editCart, arg.ID, arg.Qty, arg.Price)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.ProductName,
		&i.Qty,
		&i.Buyer,
		&i.Price,
		&i.OrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCart = `-- name: GetCart :one
SELECT id, product_name, qty, buyer, price, order_id, created_at, updated_at FROM carts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCart(ctx context.Context, id int64) (*Cart, error) {
	row := q.db.QueryRow(ctx, getCart, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.ProductName,
		&i.Qty,
		&i.Buyer,
		&i.Price,
		&i.OrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listCarts = `-- name: ListCarts :many
SELECT id, product_name, qty, buyer, price, order_id, created_at, updated_at
FROM carts
ORDER BY updated_at DESC
`

func (q *Queries) ListCarts(ctx context.Context) ([]*Cart, error) {
	rows, err := q.db.Query(ctx, listCarts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Cart{}
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.ProductName,
			&i.Qty,
			&i.Buyer,
			&i.Price,
			&i.OrderID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCart = `-- name: RemoveCart :exec
DELETE FROM carts
WHERE id = $1
`

func (q *Queries) RemoveCart(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, removeCart, id)
	return err
}

const removeCartsByOrder = `-- name: RemoveCartsByOrder :exec
DELETE FROM carts
WHERE order_id = $1
`

func (q *Queries) RemoveCartsByOrder(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, removeCartsByOrder, orderID)
	return err
}
