// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Access struct {
	ID           int64  `json:"id"`
	ApiKey       string `json:"api_key"`
	RefreshToken string `json:"refresh_token"`
	// `admin`, `guest`, `user`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Cart struct {
	ID          int64     `json:"id"`
	ProductName string    `json:"product_name"`
	Qty         int32     `json:"qty"`
	Price       float64   `json:"price"`
	OrderID     int64     `json:"order_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Order struct {
	ID          int64   `json:"id"`
	OrderNumber string  `json:"order_number"`
	Discount    float64 `json:"discount"`
	// pending, completed, cancelled
	Status    string    `json:"status"`
	Total     float64   `json:"total"`
	Buyer     string    `json:"buyer"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Payment struct {
	ID            int64  `json:"id"`
	PaymentNumber string `json:"payment_number"`
	OrderID       int64  `json:"order_id"`
	// bank, e-wallet, etc
	Method    string     `json:"method"`
	Total     float64    `json:"total"`
	PaidAt    *time.Time `json:"paid_at"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	// pending, success, failed
	Status string `json:"status"`
	// xendit, stripe, midtrans
	Gateway      *string `json:"gateway"`
	GatewayRefID *string `json:"gateway_ref_id"`
	RawResponse  []byte  `json:"raw_response"`
}
