// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order.sql

package dbgen

import (
	"context"
)

const addOrder = `-- name: AddOrder :one
INSERT INTO orders (order_number, discount, "status", total)
VALUES ($1, $2, $3, $4)
RETURNING id, order_number, discount, status, total, created_at, updated_at
`

type AddOrderParams struct {
	OrderNumber string  `json:"order_number"`
	Discount    float64 `json:"discount"`
	Status      string  `json:"status"`
	Total       float64 `json:"total"`
}

func (q *Queries) AddOrder(ctx context.Context, arg *AddOrderParams) (*Order, error) {
	row := q.db.QueryRow(ctx, addOrder,
		arg.OrderNumber,
		arg.Discount,
		arg.Status,
		arg.Total,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.Discount,
		&i.Status,
		&i.Total,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const countOrders = `-- name: CountOrders :one
SELECT COUNT(*) FROM orders
`

func (q *Queries) CountOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersByOrderNumber = `-- name: CountOrdersByOrderNumber :one
SELECT COUNT(*) FROM orders
WHERE order_number ILIKE $1
`

func (q *Queries) CountOrdersByOrderNumber(ctx context.Context, orderNumber string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByOrderNumber, orderNumber)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const editOrder = `-- name: EditOrder :one
UPDATE orders
SET discount = $2,
  "status" = $3,
  total = $4,
  updated_at = now()
WHERE id = $1
RETURNING id, order_number, discount, status, total, created_at, updated_at
`

type EditOrderParams struct {
	ID       int64   `json:"id"`
	Discount float64 `json:"discount"`
	Status   string  `json:"status"`
	Total    float64 `json:"total"`
}

func (q *Queries) EditOrder(ctx context.Context, arg *EditOrderParams) (*Order, error) {
	row := q.db.QueryRow(ctx, editOrder,
		arg.ID,
		arg.Discount,
		arg.Status,
		arg.Total,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.Discount,
		&i.Status,
		&i.Total,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, order_number, discount, status, total, created_at, updated_at FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (*Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.Discount,
		&i.Status,
		&i.Total,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const paginateOrders = `-- name: PaginateOrders :many
SELECT id, order_number, discount, status, total, created_at, updated_at FROM orders
ORDER BY updated_at DESC
LIMIT $1
OFFSET $2
`

type PaginateOrdersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) PaginateOrders(ctx context.Context, arg *PaginateOrdersParams) ([]*Order, error) {
	rows, err := q.db.Query(ctx, paginateOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.Discount,
			&i.Status,
			&i.Total,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paginateOrdersWithParams = `-- name: PaginateOrdersWithParams :many
SELECT id, order_number, discount, status, total, created_at, updated_at FROM orders
WHERE order_number ILIKE $3
ORDER BY updated_at DESC
LIMIT $1
OFFSET $2
`

type PaginateOrdersWithParamsParams struct {
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
	OrderNumber string `json:"order_number"`
}

func (q *Queries) PaginateOrdersWithParams(ctx context.Context, arg *PaginateOrdersWithParamsParams) ([]*Order, error) {
	rows, err := q.db.Query(ctx, paginateOrdersWithParams, arg.Limit, arg.Offset, arg.OrderNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.Discount,
			&i.Status,
			&i.Total,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrder = `-- name: RemoveOrder :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) RemoveOrder(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, removeOrder, id)
	return err
}
