// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package dbgen

import (
	"context"
)

const addPayment = `-- name: AddPayment :one
INSERT INTO payments (payment_number, order_id, method, total, "status", gateway)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, payment_number, order_id, method, total, paid_at, created_at, updated_at, status, gateway, gateway_ref_id, raw_response
`

type AddPaymentParams struct {
	PaymentNumber string  `json:"payment_number"`
	OrderID       int64   `json:"order_id"`
	Method        string  `json:"method"`
	Total         float64 `json:"total"`
	Status        string  `json:"status"`
	Gateway       *string `json:"gateway"`
}

func (q *Queries) AddPayment(ctx context.Context, arg *AddPaymentParams) (*Payment, error) {
	row := q.db.QueryRow(ctx, addPayment,
		arg.PaymentNumber,
		arg.OrderID,
		arg.Method,
		arg.Total,
		arg.Status,
		arg.Gateway,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNumber,
		&i.OrderID,
		&i.Method,
		&i.Total,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Gateway,
		&i.GatewayRefID,
		&i.RawResponse,
	)
	return &i, err
}

const approvePayment = `-- name: ApprovePayment :one
UPDATE payments
SET paid_at = now(),
  total = $2,
  "status" = 'success',
  gateway_ref_id = $3,
  raw_response = $4,
  updated_at = now()
WHERE id = $1
RETURNING id, payment_number, order_id, method, total, paid_at, created_at, updated_at, status, gateway, gateway_ref_id, raw_response
`

type ApprovePaymentParams struct {
	ID           int64   `json:"id"`
	Total        float64 `json:"total"`
	GatewayRefID *string `json:"gateway_ref_id"`
	RawResponse  []byte  `json:"raw_response"`
}

func (q *Queries) ApprovePayment(ctx context.Context, arg *ApprovePaymentParams) (*Payment, error) {
	row := q.db.QueryRow(ctx, approvePayment,
		arg.ID,
		arg.Total,
		arg.GatewayRefID,
		arg.RawResponse,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNumber,
		&i.OrderID,
		&i.Method,
		&i.Total,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Gateway,
		&i.GatewayRefID,
		&i.RawResponse,
	)
	return &i, err
}

const countPayments = `-- name: CountPayments :one
SELECT COUNT(*) FROM payments
`

func (q *Queries) CountPayments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPayments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentsByPaymentNumber = `-- name: CountPaymentsByPaymentNumber :one
SELECT COUNT(*) FROM payments
WHERE payment_number ILIKE $1
`

func (q *Queries) CountPaymentsByPaymentNumber(ctx context.Context, paymentNumber string) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentsByPaymentNumber, paymentNumber)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const editPayment = `-- name: EditPayment :one
UPDATE payments
SET method = $2,
  total = $3,
  gateway = $4,
  "status" = $5,
  gateway_ref_id = $6,
  raw_response = $7,
  updated_at = now()
WHERE id = $1
RETURNING id, payment_number, order_id, method, total, paid_at, created_at, updated_at, status, gateway, gateway_ref_id, raw_response
`

type EditPaymentParams struct {
	ID           int64   `json:"id"`
	Method       string  `json:"method"`
	Total        float64 `json:"total"`
	Gateway      *string `json:"gateway"`
	Status       string  `json:"status"`
	GatewayRefID *string `json:"gateway_ref_id"`
	RawResponse  []byte  `json:"raw_response"`
}

func (q *Queries) EditPayment(ctx context.Context, arg *EditPaymentParams) (*Payment, error) {
	row := q.db.QueryRow(ctx, editPayment,
		arg.ID,
		arg.Method,
		arg.Total,
		arg.Gateway,
		arg.Status,
		arg.GatewayRefID,
		arg.RawResponse,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNumber,
		&i.OrderID,
		&i.Method,
		&i.Total,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Gateway,
		&i.GatewayRefID,
		&i.RawResponse,
	)
	return &i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, payment_number, order_id, method, total, paid_at, created_at, updated_at, status, gateway, gateway_ref_id, raw_response FROM payments
WHERE payment_number = $1 LIMIT 1
`

func (q *Queries) GetPayment(ctx context.Context, paymentNumber string) (*Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, paymentNumber)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNumber,
		&i.OrderID,
		&i.Method,
		&i.Total,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Gateway,
		&i.GatewayRefID,
		&i.RawResponse,
	)
	return &i, err
}

const getPaymentByOrder = `-- name: GetPaymentByOrder :one
SELECT id, payment_number, order_id, method, total, paid_at, created_at, updated_at, status, gateway, gateway_ref_id, raw_response FROM payments
WHERE order_id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByOrder(ctx context.Context, orderID int64) (*Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrder, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNumber,
		&i.OrderID,
		&i.Method,
		&i.Total,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Gateway,
		&i.GatewayRefID,
		&i.RawResponse,
	)
	return &i, err
}

const paginatePayments = `-- name: PaginatePayments :many
SELECT id, payment_number, order_id, method, total, paid_at, created_at, updated_at, status, gateway, gateway_ref_id, raw_response FROM payments
ORDER BY updated_at DESC
LIMIT $1
OFFSET $2
`

type PaginatePaymentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) PaginatePayments(ctx context.Context, arg *PaginatePaymentsParams) ([]*Payment, error) {
	rows, err := q.db.Query(ctx, paginatePayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.PaymentNumber,
			&i.OrderID,
			&i.Method,
			&i.Total,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Gateway,
			&i.GatewayRefID,
			&i.RawResponse,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paginatePaymentsWithParams = `-- name: PaginatePaymentsWithParams :many
SELECT id, payment_number, order_id, method, total, paid_at, created_at, updated_at, status, gateway, gateway_ref_id, raw_response FROM payments
WHERE payment_number ILIKE $3
ORDER BY updated_at DESC
LIMIT $1
OFFSET $2
`

type PaginatePaymentsWithParamsParams struct {
	Limit         int32  `json:"limit"`
	Offset        int32  `json:"offset"`
	PaymentNumber string `json:"payment_number"`
}

func (q *Queries) PaginatePaymentsWithParams(ctx context.Context, arg *PaginatePaymentsWithParamsParams) ([]*Payment, error) {
	rows, err := q.db.Query(ctx, paginatePaymentsWithParams, arg.Limit, arg.Offset, arg.PaymentNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.PaymentNumber,
			&i.OrderID,
			&i.Method,
			&i.Total,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Gateway,
			&i.GatewayRefID,
			&i.RawResponse,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
