// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Cart Cart item model
type Cart struct {
	Buyer       string `json:"buyer"`
	CreatedAt   string `json:"created_at"`
	Id          int64  `json:"id"`
	OrderId     int64  `json:"order_id"`
	Price       int    `json:"price"`
	ProductName string `json:"product_name"`
	Qty         int32  `json:"qty"`
	UpdatedAt   string `json:"updated_at"`
}

// CartCreateInput Create cart item model
type CartCreateInput struct {
	Buyer       string `json:"buyer"`
	OrderId     int64  `json:"order_id"`
	Price       int    `json:"price"`
	ProductName string `json:"product_name"`
	Qty         int32  `json:"qty"`
}

// CartListSuccessResponse defines model for CartListSuccessResponse.
type CartListSuccessResponse struct {
	// Code Success code
	Code int `json:"code"`

	// Data List of cart items
	Data []Cart `json:"data"`

	// Message Success message
	Message string `json:"message"`

	// Status Success status
	Status string `json:"status"`
}

// CartSuccessResponse defines model for CartSuccessResponse.
type CartSuccessResponse struct {
	// Code Success code
	Code int `json:"code"`

	// Data Cart item model
	Data Cart `json:"data"`

	// Message Success message
	Message string `json:"message"`

	// Status Success status
	Status string `json:"status"`
}

// ErrorResponse Represents an error response from the API.
type ErrorResponse struct {
	// Code Error code
	Code int `json:"code"`

	// Message Error message
	Message string `json:"message"`

	// Status Error status
	Status string `json:"status"`
}

// MetaData Metadata about the response
type MetaData struct {
	// Page Current page number
	Page *int32 `json:"page,omitempty"`

	// Size Number of items per page
	Size *int32 `json:"size,omitempty"`

	// TotalData Total number of items
	TotalData *int64 `json:"total_data,omitempty"`

	// TotalPages Total number of pages
	TotalPages *int32 `json:"total_pages,omitempty"`
}

// Order Order item model
type Order struct {
	CreatedAt   string  `json:"created_at"`
	Discount    float32 `json:"discount"`
	Id          int64   `json:"id"`
	OrderNumber string  `json:"order_number"`
	Status      string  `json:"status"`
	Total       float32 `json:"total"`
	UpdatedAt   string  `json:"updated_at"`
}

// OrderCreateInput Create order item model
type OrderCreateInput struct {
	Discount    int    `json:"discount"`
	OrderNumber string `json:"order_number"`
	Status      string `json:"status"`
	Total       int    `json:"total"`
}

// OrderPaginateSuccessResponse defines model for OrderPaginateSuccessResponse.
type OrderPaginateSuccessResponse struct {
	// Code Success code
	Code int `json:"code"`

	// Data List of order items
	Data []Order `json:"data"`

	// Message Success message
	Message string `json:"message"`

	// Meta Metadata about the response
	Meta MetaData `json:"meta"`

	// Status Success status
	Status string `json:"status"`
}

// OrderSuccessResponse defines model for OrderSuccessResponse.
type OrderSuccessResponse struct {
	// Code Success code
	Code int `json:"code"`

	// Data Order item model
	Data Order `json:"data"`

	// Message Success message
	Message string `json:"message"`

	// Status Success status
	Status string `json:"status"`
}

// OrderUpdateInput Update order item model
type OrderUpdateInput struct {
	Discount int    `json:"discount"`
	Status   string `json:"status"`
	Total    int    `json:"total"`
}

// IdParam defines model for IdParam.
type IdParam = int32

// OrderNumberParam defines model for OrderNumberParam.
type OrderNumberParam = string

// PageParam defines model for PageParam.
type PageParam = int32

// SizeParam defines model for SizeParam.
type SizeParam = int32

// ListOrdersParams defines parameters for ListOrders.
type ListOrdersParams struct {
	// Page The page number to retrieve
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// Size The size of the data to retrieve
	Size *SizeParam `form:"size,omitempty" json:"size,omitempty"`

	// OrderNumber The order number of the data to remove
	OrderNumber *OrderNumberParam `form:"order_number,omitempty" json:"order_number,omitempty"`
}

// AddCartJSONRequestBody defines body for AddCart for application/json ContentType.
type AddCartJSONRequestBody = CartCreateInput

// AddOrderJSONRequestBody defines body for AddOrder for application/json ContentType.
type AddOrderJSONRequestBody = OrderCreateInput

// EditOrderJSONRequestBody defines body for EditOrder for application/json ContentType.
type EditOrderJSONRequestBody = OrderUpdateInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all carts
	// (GET /cart)
	ListCarts(c *fiber.Ctx) error
	// Add a new cart
	// (POST /cart)
	AddCart(c *fiber.Ctx) error
	// Remove a cart
	// (DELETE /cart/{id})
	RemoveCart(c *fiber.Ctx, id IdParam) error
	// List all orders
	// (GET /order)
	ListOrders(c *fiber.Ctx, params ListOrdersParams) error
	// Add a new order
	// (POST /order)
	AddOrder(c *fiber.Ctx) error
	// Detail an order
	// (GET /order/{id})
	ShowOrder(c *fiber.Ctx, id IdParam) error
	// Update an existing order
	// (PUT /order/{id})
	EditOrder(c *fiber.Ctx, id IdParam) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// ListCarts operation middleware
func (siw *ServerInterfaceWrapper) ListCarts(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.ListCarts(c)
}

// AddCart operation middleware
func (siw *ServerInterfaceWrapper) AddCart(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.AddCart(c)
}

// RemoveCart operation middleware
func (siw *ServerInterfaceWrapper) RemoveCart(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("form", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.RemoveCart(c, id)
}

// ListOrders operation middleware
func (siw *ServerInterfaceWrapper) ListOrders(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrdersParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameter("form", true, false, "size", query, &params.Size)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter size: %w", err).Error())
	}

	// ------------- Optional query parameter "order_number" -------------

	err = runtime.BindQueryParameter("form", true, false, "order_number", query, &params.OrderNumber)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter order_number: %w", err).Error())
	}

	return siw.Handler.ListOrders(c, params)
}

// AddOrder operation middleware
func (siw *ServerInterfaceWrapper) AddOrder(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.AddOrder(c)
}

// ShowOrder operation middleware
func (siw *ServerInterfaceWrapper) ShowOrder(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("form", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.ShowOrder(c, id)
}

// EditOrder operation middleware
func (siw *ServerInterfaceWrapper) EditOrder(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdParam

	err = runtime.BindStyledParameterWithOptions("form", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.EditOrder(c, id)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/cart", wrapper.ListCarts)

	router.Post(options.BaseURL+"/cart", wrapper.AddCart)

	router.Delete(options.BaseURL+"/cart/:id", wrapper.RemoveCart)

	router.Get(options.BaseURL+"/order", wrapper.ListOrders)

	router.Post(options.BaseURL+"/order", wrapper.AddOrder)

	router.Get(options.BaseURL+"/order/:id", wrapper.ShowOrder)

	router.Put(options.BaseURL+"/order/:id", wrapper.EditOrder)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3W7bOhJ+FYK7V4HqyE7SBXy1bpICKbZt0GRPL9IgZcSxzR6JVEiqrRv43Q/4I1mW",
	"qFhu3aQFehdZ5Px833BmOMo9TkSWCw5cKzy+xzmRJAMN0j6d0XPzbP6koBLJcs0Ex2N8OQd0doLEFOk5",
	"IEo0QVogCZn4DDjC8JVkeQp4PIwwM+tzouc4wpxkgMeYURxhCXcFk0DxWMsCIqySOWTEqJoKmRFt1nF9",
	"MMIR1osc3CPMQOJlhJVeGPF2qXl+KynIN0V2C7KymKSp+HKa5XrxF0kLKPW0HRFmM+J292aX8Nt3J8PR",
	"weHRc+yduytALlbeWXE3Thyu+8WLNCW3aWWJd0tpyfgs5NU5mcH27uRkBqU31gMtGYRpaVhuduIHmehw",
	"4QFmLti37/BBsW/QpiLgSBz2xOzfrSfLUpo9GMdE6vapML8ipiFDmaCQ4gjnUuQgNQO767ZYgDR/tJhP",
	"JBAN9Ibo4GtGmz48PwyeCxd7vZfnkiWwtnaaCqI71gpaJPrGIRww8k4vep7eIqfd3i7rqeHK5Yo13U5T",
	"5NEsnaj5vgbnmrbryhpx+wkSbYwxpB3b9Wc8L0Ks2pco+W5yfwdSGqhvB3gXrP9jSl8USQJKvQOVC66s",
	"keu4JYJCG3S/Ddm3tQM/iuMQDiZHtIUY/SaLVNSpuqirijP8Ssw5OhGwHjpjPIpHB8+G8bN4iIajcRyP",
	"4xi70zis0zocHVS0DY2B67TgC6sRnbtfPZ7j0fpBCCpbXkfYGT6+x/+WMMVj/K/9Vcne9zlp3yakZQUN",
	"kZIszHMGSpms3glwuaBe4ao8pqqkS5FyG6ZFmi5wsHgRXahuRf59XY8X2ZbWiEbL7sqXCPuo8CK7wu9x",
	"Q68POz/GBkpNPP+ujJxKKWSdi3Wj3kEuQRnUEOEIzGIk/Wo0lSKzvcDk/GzQyrxhGq2+FomHYRI7iXFS",
	"QrScmLaEC42mouB0G/ydzAD61uuN2G8D+mvQ5CSYG80b21mRW1FoC24JdwvgPAjNcSElcF3vNxs9Zp9G",
	"3jRqLdFvql7cZaEcJMobBJjWr4cCLTRJb8L14dK8qzX+rRJx1NDRUbGdDmOg2qzELasriXqV5xa39s7T",
	"1md/fqhR2dBrUqYSUXD9UAfi2d6+M/UbQ3pXp6X1yuLbz56tW8vGba3yvjKoVL9dV2lZ6NNWik109eHj",
	"sXDuahd7g9gJ1TmZMU40/Art4oqSZr/Yozlc0TWMB0eNZrGkZW2GUBKCc+DUMFERMTyKB/852mWb6HLG",
	"rvrEVarZplHMYHPDVNWtR2pjtu5mrOu/ToNZ8fqDPP7eLab14//2sHQkXfdy50n3Z+TUbZKoMQGSQjK9",
	"uDAR4ScSQCTISaHnq6eXpRWv3l/i5uTtlGuQaCEKifb2Xr2/RC/sHnQp/ga+t4e0QKTQcyHZN9Mt3hWg",
	"tBog9IGfOnrH6OPELyBG5riU8KGI44PESH6mjTD7DB8/8HJIZ7xxFq6QmWud46VxjvGpcOeJa5JYViAj",
	"LMVjnA0IJ3zGC/nfmflpkIhsNQd8LeYkywhFE7PInqY1jyfnZ2hqGnzCTQGaITUXeW7+SIjUFnKmbdhe",
	"lC/sdWxyfoYj/BmkcnKGg9gW3xw4yRke44NBPDgwYUX03JKxn/iR4Qx06PbjTpxCxB1BMUUkTRvmDCxe",
	"Jk4tumfUF61jb2vZwFuFozguIQMXyCTPU5bYrfuflNF7X5uQbrq/hoY5lpwGomnqsVtG+DA+3JkN6/fH",
	"gObGhWwZ4aMdQrBR/UvCUqD1QXWJgzmdRZYRuSibDFKBFGFNZsqcdzsjuF5GOBcqECETSk1wcPjixlla",
	"2DubWigN2aAVFhNKrUCXU0DpF4IudhoP9eZ2uZ68tCxg2QrH4U7V9whFe1IJpfCUwUAotYQ1wmBCaY3N",
	"dhgsI5cx9u8ZXbpoSEEH5yaZcHnDhkU1KfGBEcgYboePjvr3vquw06sl++X3QNNvNtg9fGx2nRtPe86N",
	"BSF2nW2ekzC5ory9b1UP7C41CFYB2/2orTldfWRcRhsXr77m9Vjc+igbCJvdEffgNbKjUDk4/1SqCohw",
	"qRJlZJVx7K4bvYqVa7U3Vysn8ueUq9Yw5pHrVfCyGCDG3cP8kOGJa5bLT11FS3i2mgFRZbaqbm1Ib/YD",
	"P2jCUmVzHFI5JGzKEqeiHSoXc/GljJWdFa/4iaj2nv9JQOEEdGLhQYR3xluEH7jmf0d0nVKmdxFdPymH",
	"1WcbvXLYUwW2n1g+YWQVtUlPI6z8EIhwBF+Z0uZ63ZnPapMV9x8DtZnK1bUh229pfYYp40ohCakBw1jV",
	"Gi/4OYX/QNxPSFWO/WY//Lte/hMAAP//X4Vr5s0nAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
